version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"
      prod-deps:
        dependency-type: "production"
        patterns:
          - "*"