#!/bin/bash

npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting commit."
  exit 1
fi

npm run format
npm run type-check

if [ $? -ne 0 ]; then
  echo "Type checking failed. Aborting commit."
  exit 1
fi

# Store the edited files in an array
edited_files=()

# Check if any files are staged for commit
if [[ -n $(git diff --name-only --cached --diff-filter=d) ]]; then
  # Get the list of edited files (excluding deleted files)
  edited_files=($(git diff --name-only --cached --diff-filter=d))
fi

# Add the formatted files back to the staging area
if [[ ${#edited_files[@]} -gt 0 ]]; then
  echo "Adding formatted files back to the staging area..."
  git add "${edited_files[@]}"
fi
