#!/bin/bash

npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting push."
  exit 1
fi

npm test

# check if any tests failed
if [ $? -ne 0 ]; then
  echo "Test(s) failed. Aborting push."
  exit 1
fi


BRANCH=$(git symbolic-ref --short HEAD)
if [ "$BRANCH" = "master" ]; then
  VERSION=$(node -pe "require('./package.json').version")
  NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
  npm --no-git-tag-version version $NEW_VERSION

  git add package.json
  git add package-lock.json

  git commit -m "AUTOMATIC: build + bump version to $NEW_VERSION"

  git tag -a v$NEW_VERSION -m "Version $NEW_VERSION"

  git push --no-verify
  git push --no-verify --tags

  # failing original git push. Due to the fact a new commit has been added and pushed by itself.
  echo "Version got bumped and a build got triggered. This has added a new commit and pushed by itself. So original push is no longer required.";
  exit 1;
fi