#!/bin/bash

npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting push."
  exit 1
fi

npm test

# check if any tests failed
if [ $? -ne 0 ]; then
  echo "Jest test(s) failed. Aborting push."
  exit 1
fi


BRANCH=$(git symbolic-ref --short HEAD)
if [ "$BRANCH" = "master" ]; then
  npm run build

  VERSION=$(node -pe "require('./package.json').version")
  NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
  npm version $NEW_VERSION

  git add package.json
  git add dist/*

  git tag -a v$NEW_VERSION -m "Version $NEW_VERSION"

  git commit -m "AUTOMATIC: build + bump version to $NEW_VERSION"

  git push --no-verify --tags
fi